use clictell_auto_etl;
go
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create procedure master.correct_makemodelyear
(
	@make varchar(100) = 'APRILI'
	,@model varchar(100) = 'RSV45'
	,@modelyear int = 20
)
AS
/*
Developer			role			date		Details
Srikanth.K			developed		6/2/2022	Correct Make Model Year of vehicle, insert in master.vehicle_makemodel table and return the corrected data
*/
BEGIN
	drop table if exists #temp
	select @make as make,@model as model,@modelyear as modelyear into #temp

	update #temp set make =
		upper(case when Make in ('APRILLA', 'APRILI', 'APRILIA', 'APRILI','APRILLIA', 'AP') then 'APRILIA' 
				   when Make in ('POLARI', 'POLORI', 'POLAR', 'POLA', 'POL', 'POALRI', 'POALAR' ,'POLAI', 'POL.', 'PLO','POLARIS','Polaris Industries','POLARIS TRAILERS', 'PLARIS') then 'POLARIS' 
				   when Make in ('Yam','YA','YAHAHA','YAHMA','YAMA','YAMAH','YAMAHA','Yamaha Power','YAMAHA WATERCRAFT','YAMAHA-2','yamaha1','YAMMAH','YAMXVS') then 'YAMAHA' 
				   when Make in ('CHEVROL','CHEVROLET','CHEVY', 'CHEV') then 'CHEVROLET'
				   when Make in ('CAN AM','CAN-AM','CANAM', 'CANNONDALE') then 'CAN-AM'
				   when Make in ('H', 'H.D', 'H.D.', 'HD', 'H-D', 'Hearley', 'Harley','HARLEY DAVIDSON', 'FXRS', 'HARLEY D') then  'HARLEY-DAVIDSON'
				   when Make in ('KAW','KAWA','KAWASA','KAWASK','KAWK', 'KAWAS', 'KAWASKI', 'KAWAASAKI', 'KA') then 'KAWASAKI'
				   when Make in ('MOTOG','MOTOGU') then 'MOTO GUZZI'
				   when Make in ('ROYAL  ENFIELD') then  'ROYEL ENFIELD'
				   when Make in ('ULTRA CUSTOM') then 'ULTRA'
				   when Make in ('Acc') then 'ACCESS'
				   when Make in ('B/DOG', 'BIG Do') then 'BIGDOG'
				   when make in ('HND', 'HOND', 'HODNA', 'HONDA  MOWER', 'HONDA POWER', 'HONDA`', 'HIONDA', 'HONDA GL', 'HO') then 'HONDA'
				   when (make like '%honda?%' or make like '%honda/%' or make like '%HONDA SHADOW%') then 'HONDA'
				   when make in ('ARTIC CAT', 'ARCTIC', 'ARTIC', 'A/C', 'AC', 'ARCTIC')		then		'ARCTIC CAT'
				   when make in ('CF MOTO')		then		'CFMOTO'
				   when make in ('CHANGZH', 'Changhou Yamaski', 'CHANGZHOU')		then		'CHANGZHOU NANXIASHU'
				   when make in ('DUCA')		then		'DUCATI'
				   when make in ('EZLDR','EZLOADER')		then		'EZ LOADER'
				   when make in ('ROYAL INFIELD')	then		'ROYAL ENFIELD'
				   when make in ('SEA - DOO','SEA DOO', 'SEA-DOO', 'SKI DOO')	then		'SEADOO'
				   when make in ('TAO TAO', 'TOW GO')			then		'TAOTAO'
				   when make in ('YAMAHA BLACK','YAMAHYA','YAMAMA','YAMHA','YZFR6TB')		then	'YAMAHA'
				   when make in ('SUZ', 'SUZI', 'SUZU', 'SUZUKU', 'SUZUZKI') then 'SUZUKI'
				   when make in ('CHRYSL') then 'CHRYSLER'
				   when make in ('TRIUMP', 'TRIU') then 'TRIUMPH'
				   when make in ('VICTO', 'VICTOR') then 'VICTORY'
				   when make in ('TM', 'THUNDE', 'THND M') then 'Thunder Mountain'
				   when make in ('THOROU') then 'THOROUGHBRED'
				   when make in ('INDEPE') then 'INDEPENDENCE'
				   when make in ('HARDCO') then 'HARDCORE'
				   when make in ('DUTCHM') then 'DUTCHMEN'
				   when make in ('AMER') then 'AMERICAN'
				   when make in ('BH') then 'Boss Hoss'
				   when make in ('VOLKSWAG', 'VW') then 'VOLKSWAGEN'
				   when make in ('MVAUGUSTA') then 'MV-AGUSTA'
				   when make in ('CADILL') then 'CADILLAC'
				   when make in ('Chinese ATV, Scooter & Mi') then 'TAOTAO'
				   when make in ('BM', 'BWM') then 'BMW'
				   when make in ('Buel', 'EBR') then 'BUELL'
				   when make in ('ADLEY') then 'ADLY'
				   when make in ('Coleman') then 'Coleman Powersports'
				   when make in ('CUBCAD') then 'Cub Cadet'
				   when make in ('DROPTA') then 'DROPTAIL'
				   when make in ('LA') then 'Land Rover'
				   when make in ('JETMO') then 'Jet Moto'
				   when make in ('ZHEJIANG KA') then 'ZHEJIA'
			else Make end)

	update #temp set model =
			upper(case 
				WHEN	(model like 'RSV4%' )  and make ='APRILIA'		THEN	'RSV4'
				WHEN	(model like 'TUONO%' or model like 'TUORO%' or model like 'TUANO%' or model like 'TOUNO%')  and make ='APRILIA' THEN  'TUONO'
				WHEN	(model like 'WILD%CAT%' )  and make ='ARCTIC CAT'	THEN	'WILDCAT'
				WHEN	(model like '%RANGER%' )  and make ='POLARIS'		THEN	'RANGER'
				WHEN	(model like '%RAZOR%' )  and make ='POLARIS'		THEN	'RAZOR'
				WHEN	(model like '%PREDATOR%' )  and make ='POLARIS'		THEN	'PREDATOR'
				WHEN	(model like '%TRAIL%BLAZER%' )  and make ='POLARIS'	THEN	'TRAIL BLAZER'
				WHEN	(model like '%SCRAMBLER%' )  and make ='POLARIS'	THEN	'SCRAMBLER'
				WHEN	(model like '%TRAIL BOSS%' )  and make ='POLARIS'	THEN	'TRAIL BOSS'
				WHEN	(model like '%SPORTSMAN%' )  and make ='POLARIS'	THEN	'SPORTSMAN'
				WHEN	(model like '%SPRTSMN%' )  and make ='POLARIS'		THEN	'SPRTSMN'
				WHEN	(model like '%SPTM%' )  and make ='POLARIS'			THEN	'SPTM'
				WHEN	(model like '%SPTMN%' )  and make ='POLARIS'		THEN	'SPTMN'
				WHEN	(model like '%XPLORER%' )  and make ='POLARIS'		THEN	'XPLORER'
				WHEN	(model like '%SPRTSMN%' )  and make ='POLARIS'		THEN	'SPRTSMN'
				WHEN	(model like '%RZR%' )  and make ='POLARIS'			THEN	'RZR'
				WHEN	(model like '%OUTLAW%' )  and make ='POLARIS'		THEN	'OUTLAW'
				WHEN	(model like '%MAGNUM%'  )  and make ='POLARIS'		THEN	'MAGNUM'
				WHEN	(model like '%HAWKEYE%' )  and make ='POLARIS'		THEN	'HAWKEYE'
				WHEN	(model like '%RGR%' )  and make ='POLARIS'			THEN	'RGR'
				WHEN	(model like '%SCRAM%' )  and make ='POLARIS'		THEN	'SCRAMBLER'
				WHEN	(model like '%SCAM%' )  and make ='POLARIS'			THEN	'SCRAMBLER'
				when (model like '%1100RT%' )  and make ='BMW' THEN 'RT'
			 when (model like '%1100S%' )  and make ='BMW' THEN '1100'
			 when (model like '%1150RA%' )  and make ='BMW' THEN '1150'
			 when (model like '%1150RT%' )  and make ='BMW' THen '1150'
			 when (model like '%1200 RT%')  and make ='BMW' THEN 'RT'
			 when (model like '%1600%')  and make ='BMW' THEN '1600'
			 when (model like '750%')  and make ='BMW' then '750'
			 when (model like 'F650GS%')  and make ='BMW' then 'F650GS'
			 when (model like 'G310%')  and make ='BMW' then 'G310'
			 when (model like 'G650%')  and make ='BMW' then 'G650'
			 when (model like 'K100%')  and make ='BMW' then 'K100'
			 when (model like 'K1200%')  and make ='BMW' then 'K1200'
			 when (model like 'K1300%')  and make ='BMW' then 'K1300'
			 when(model like 'K1600%')  and make ='BMW' then 'K1600'
			 when (model like 'K75%')  and make ='BMW' then 'K75'
			 when (model like 'R1100%')  and make ='BMW' then 'R1100'
			 when (model like 'R1150%')  and make ='BMW' then 'R1150'
			 when (model like 'R1200%')  and make ='BMW' then 'R1200'
			 when (model like 'S 1000%')  and make ='BMW' then 'S 1000'
			 when (model like 'X3%')  and make ='BMW' then 'X3'
			 when (model like 'X5%')  and make ='BMW' then 'X5'
			 when (model like 'FISH PRO%')  and make ='BOMBARDIER' then 'FISH PRO'
			 when (model like 'GTI 90%')  and make ='BOMBARDIER' then 'GTI 90'
			 when (model like 'GTR 230%')  and make ='BOMBARDIER' then 'GTR 230'
			 when (model like 'GTX%')  and make ='BOMBARDIER' then 'GTX'
			 when (model like 'QUEST%')  and make ='BOMBARDIER' then 'QUEST'
			 when (model like 'RXT%')  and make ='BOMBARDIER' then 'RXT'
			 when (model like 'SPARK 2UP%')  and make ='BOMBARDIER' then 'SPARK 2UP'
			 when (model like 'SPARK 3UP%')  and make ='BOMBARDIER' then 'SPARK 3UP'
			 when (model like 'SPEEDSTER%')  and make ='BOMBARDIER' then 'SPEEDSTER'
			 when (model like 'WAKE%')  and make ='BOMBARDIER' then 'WAKE'
			 when (model like 'A4%')  and make ='CAN-AM' then 'A4'
			 when (model like 'B9%')  and make ='CAN-AM' then 'B9'
			 when (model like 'C01000MAX%')  and make ='CAN-AM' then 'C01000MAX'
			 when (model like 'CO1000%')  and make ='CAN-AM' then 'CO1000'
			 when (model like 'CO10%')  and make ='CAN-AM' then 'CO10'
			 when (model like 'COM LTD%')  and make ='CAN-AM' then 'COM LTD'
			 when (model like 'COM1000%')  and make ='CAN-AM' then 'COM1000'
			 when (model like 'COM800%')  and make ='CAN-AM' then 'COM800'
			 when (model like 'COMM DPS%')  and make ='CAN-AM' then 'COMM DPS'
			 when (model like 'COMM LTD%')  and make ='CAN-AM' then 'COMM LTD'
			 when (model like 'COMM XT%')  and make ='CAN-AM' then 'COMM XT'
			 when (model like 'COMMANDER%')  and make ='CAN-AM' then 'COMMANDER'
			 when (model like 'DEF BASE%')  and make ='CAN-AM' then 'DEF BASE'
			 when (model like 'DEF HD5%')  and make ='CAN-AM' then 'DEF HD5'
			 when (model like 'DEF MAX%')  and make ='CAN-AM' then 'DEF MAX'
			 when (model like 'DEF XT%')  and make ='CAN-AM' then 'DEF XT'
			 when (model like 'DEFENDER LTD%')  and make ='CAN-AM' then 'DEFENDER LTD'
			 when (model like 'DEFENDER MAX%')  and make ='CAN-AM' then 'DEFENDER MAX'
			 when (model like 'DEF HD5%')  and make ='CAN-AM' then 'DEF HD5'
			 when (model like 'DEFPRO%')  and make ='CAN-AM' then 'DEFPRO'
			 when (model like 'DS%')  and make ='CAN-AM' then 'DS'
			 when (model like 'E6%')  and make ='CAN-AM' then 'E6'
			 when (model like 'F3 LTD%')  and make ='CAN-AM' then 'F3 LTD'
			 when (model like 'F3 S%')  and make ='CAN-AM' then 'F3 S'
			 when (model like 'MAV MAX%')  and make ='CAN-AM' then 'MAV MAX'
			 when (model like 'MAV SPORT%')  and make ='CAN-AM' then 'MAV SPORT'
			 when (model like 'MAV TRAIL%')  and make ='CAN-AM' then 'MAV TRAIL'
			 when (model like 'MAV X3%')  and make ='CAN-AM' then 'MAV X3'
			 when (model like 'MAV XC%')  and make ='CAN-AM' then 'MAV XC'
			 when (model like 'MAV XRC%')  and make ='CAN-AM' then 'MAV XRC'
			 when (model like 'MAV XRS%')  and make ='CAN-AM' then 'MAV XRS'
			 when (model like 'MAV1000%')  and make ='CAN-AM' then 'MAV1000'
			 when (model like 'MAVERICK%')  and make ='CAN-AM' then 'MAVERICK'
			 when (model like 'MAVX3%')  and make ='CAN-AM' then 'MAVX3'
			 when (model like 'OL1000%')  and make ='CAN-AM' then 'OL1000'
			 when (model like 'OL450%')  and make ='CAN-AM' then 'OL450'
			 when (model like 'OL500%')  and make ='CAN-AM' then 'OL500'
			 when (model like 'OL570%')  and make ='CAN-AM' then 'OL570'
			 when (model like 'OL650%')  and make ='CAN-AM' then 'OL650'
			 when (model like 'OL800%')  and make ='CAN-AM' then 'OL800'
			 when (model like 'OL850%')  and make ='CAN-AM' then 'OL850'
			 when (model like 'OLMax%')  and make ='CAN-AM' then 'OLMax'
			 when (model like 'OLM100%')  and make ='CAN-AM' then 'OLM100'
			 when (model like 'OLM450%')  and make ='CAN-AM' then 'OLM450'
			 when (model like 'OLM650%')  and make ='CAN-AM' then 'OLM650'
			 when (model like 'OLM8002M%')  and make ='CAN-AM' then 'OLM8002M'
			 when (model like 'OLN MAX%')  and make ='CAN-AM' then 'OLN MAX'
			 when (model like 'OLN XTP%')  and make ='CAN-AM' then 'OLN XTP'
			 when (model like 'OLNDR%')  and make ='CAN-AM' then 'OLNDR'
			 when (model like 'OLXT6502P%')  and make ='CAN-AM' then 'OLXT6502P'
			 when (model like 'OTLNDR%')  and make ='CAN-AM' then 'OTLNDR'
			when (model like 'OUTLANDER%')  and make ='CAN-AM' then 'OUTLANDER'
			when (model like 'OUTLNDR%')  and make ='CAN-AM' then 'OUTLNDR'
			when (model like 'RD SPYDER%')  and make ='CAN-AM' then 'RD SPYDER'
			when (model like 'REN XMR%')  and make ='CAN-AM' then 'REN XMR'
			when (model like 'REN1000RX%')  and make ='CAN-AM' then 'REN1000'
			when (model like 'REN10XXC%')  and make ='CAN-AM' then 'REN10XXC'
			when (model like 'RENEGADE%')  and make ='CAN-AM' then 'RENEGADE'
			when (model like 'ROADSTER%')  and make ='CAN-AM' then 'ROADSTER'
			when (model like 'RT LTD%')  and make ='CAN-AM' then 'RT LTD'
			when (model like 'RT-S%')  and make ='CAN-AM' then 'RT-S'
			when (model like 'RTLTDSE6%')  and make ='CAN-AM' then 'RTLTDSE6'
			when (model like 'RTS%')  and make ='CAN-AM' then 'RTS'
			when (model like 'RYKER%')  and make ='CAN-AM' then 'RYKER'
			when (model like 'SPY F3%')  and make ='CAN-AM' then 'SPY F3'
			when (model like 'SPY RT%')  and make ='CAN-AM' then 'SPY RT'
			when (model like 'SPYDER%')  and make ='CAN-AM' then 'SPYDER'
			when  (model like 'SPYDRT%')  and make ='CAN-AM' then 'SPYDRT'
			when (model like 'SPYRT%')  and make ='CAN-AM' then 'SPYRT'
			when (model like 'ST-S%')  and make ='CAN-AM' then 'ST-S'
			when (model like 'x3%')  and make ='CAN-AM' then 'x3'
			when (model like 'DIAVEL%')  and make ='DUCATI' then 'DIAVEL'
			when (model like 'HYM%')  and make ='DUCATI' then 'HYM'
			when (model like 'HYPER%')  and make ='DUCATI' then 'HYPER'
			when (model like 'M696%')  and make ='DUCATI' then 'M696'
			when (model like 'M796%')  and make ='DUCATI' then 'M796'
			when (model like 'MONSTER%')  and make ='DUCATI' then 'MONSTER'
			when (model like 'MS1200%')  and make ='DUCATI' then 'MS1200'
			when (model like 'MTS%')  and make ='DUCATI' then 'MTS'
			when (model like 'MULTI STRADA%')  and make ='DUCATI' then 'MULTI STRADA'
			when (model like 'PAN1199AB%')  and make ='DUCATI' then 'PAN1199AB'
			when (model like 'PANIGALE%')  and make ='DUCATI' then 'PANIGALE'
			when (model like 'SCR800C%')  and make ='DUCATI' then 'SCR800C'
			when (model like 'SCRAMBLER%')  and make ='DUCATI' then 'SCRAMBLER'
			when (model like 'SPORT CLASSIC%')  and make ='DUCATI' then 'SPORT CLASSIC'
			when  (model like 'EX%')  and make ='GASGAS' then 'EX'
			when (model like 'VT750CDC%')  and make ='HONDA' then 'VT750CDC'
			when (model like '1000%')  and make ='HONDA' then '1000'
			when (model like '125%')  and make ='HONDA' then '125'
			when (model like '150%')  and make ='HONDA' then '150'
			when (model like '250%')  and make ='HONDA' then '250'
			when (model like '400%')  and make ='HONDA' then '400'
			when (model like '600%')  and make ='HONDA' then '600'
			when (model like '650%')  and make ='HONDA' then '650'
			when (model like '700%')  and make ='HONDA' then '700'
			when (model like '80%')  and make ='HONDA' then '80'
			when (model like 'ACCORD%')  and make ='HONDA' then 'ACCORD'
			when (model like 'ADV150%')  and make ='HONDA' then 'ADV150'
			when (model like 'AERO%')  and make ='HONDA' then 'AERO'
			when (model like 'AFRICA%')  and make ='HONDA' then 'AFRICA'
			when (model like 'BF%')  and make ='HONDA' then 'BF100'
			when (model like 'C125A%')  and make ='HONDA' then 'C125A'
			when (model like 'CB1000%')  and make ='HONDA' then 'CB1000'
			when (model like 'CB1100%')  and make ='HONDA' then 'CB1100'
			when (model like 'CB125%')  and make ='HONDA' then 'CB125'
			when (model like 'CB250%')  and make ='HONDA' then 'CB250'
			when (model like 'CB300%')  and make ='HONDA' then 'CB300'
			when (model like 'CB400%')  and make ='HONDA' then 'CB400'
			when (model like 'CB450%')  and make ='HONDA' then 'CB450'
			when (model like 'CB500%')  and make ='HONDA' then 'CB500'
			when (model like 'CB550%')  and make ='HONDA' then 'CB550'
			when (model like 'CB600F%')  and make ='HONDA' then 'CB600F'
			when (model like 'CB650%')  and make ='HONDA' then  'CB650'
			when (model like 'CB700%')  and make ='HONDA' then 'CB700'
		   when (model like 'CB750%')  and make ='HONDA' then 'CB750'
		   when (model like 'CB900%')  and make ='HONDA' then 'CB900'
		   when (model like 'CBR 600%')  and make ='HONDA' then 'CBR 600' 
		   when (model like 'CBR1000%')  and make ='HONDA' then 'CBR1000'
		   when (model like 'CBR10%')  and make ='HONDA' then 'CBR10'
		   when (model like 'CBR1100%')  and make ='HONDA' then 'CBR1100'
		   when (model like 'CBR250%')  and make ='HONDA' then 'CBR250'
		   when (model like 'CBR300%')  and make ='HONDA' then 'CBR300'
		   when (model like 'CBR500%')  and make ='HONDA' then 'CBR500'
		   when (model like 'CBR600%')  and make ='HONDA' then 'CBR600'
		   when (model like 'CBR650%')  and make ='HONDA' then 'CBR650'
		   when (model like 'CBR900%')  and make ='HONDA' then 'CBR900'
		   when (model like 'CBR929%')  and make ='HONDA' then 'CBR929'
		   when (model like 'CBR954%')  and make ='HONDA' then 'CBR954'
		   when (model like 'CHF50%')  and make ='HONDA' then 'CHF50'
		   when (model like 'CIVIC%')  and make ='HONDA' then 'CIVIC'
		   when (model like 'CIVIC SI%')  and make ='HONDA' then 'CIVIC SI'
		   when (model like 'CL%')  and make ='HONDA' then 'CL'
		   when (model like 'CMX1100%')  and make ='HONDA' then 'CMX1100'
		   when (model like 'CMX250%')  and make ='HONDA' then 'CMX250'
		   when (model like 'CMX300%')  and make ='HONDA' then 'CMX300'
		   when (model like 'CMX450%')  and make ='HONDA' then 'CMX450'
		   when (model like 'CMX500%')  and make ='HONDA' then 'CMX500'
		   when (model like 'CN250%')  and make ='HONDA' then 'CN250'
		   when (model like 'CR 85%')  and make ='HONDA' then 'CR 85'
		   when (model like 'CR-V%')  and make ='HONDA' then 'CR-V'
		   when (model like 'CR-Z%')  and make ='HONDA' then 'CR-Z'
		   when (model like 'CR125%')  and make ='HONDA' then 'CR125'
		   when (model like 'CR150%')  and make ='HONDA' then 'CR150'
		   when (model like 'CR250%')  and make ='HONDA' then 'CR250'
		   when (model like 'CR500%')  and make ='HONDA' then 'CR500'
		   when (model like 'CR80%')  and make ='HONDA' then 'CR80'
		   when (model like 'CR85%')  and make ='HONDA' then 'CR85'
		   when (model like 'CRF 450 %')  and make ='HONDA' then 'CRF 450'
		   when (model like 'CRF1000%')  and make ='HONDA' then 'CRF1000'
		   when (model like '%CRF100%')  and make ='HONDA' then 'CRF100'
		   when (model like 'CRF110%')  and make ='HONDA' then 'CRF110'
		   when (model like 'CRF125%')  and make ='HONDA' then 'CRF125'
		   when (model like 'CRF150%')  and make ='HONDA' then 'CRF150'
		   when (model like 'CRF230%')  and make ='HONDA' then 'CRF230'
		   when (model like 'CRF250%')  and make ='HONDA' then 'CRF250'
		   when (model like 'CRF300%')  and make ='HONDA' then 'CRF300'
		   when (model like 'CRF450%')  and make ='HONDA' then 'CRF450'
		   when (model like 'CRF50%')  and make ='HONDA' then 'CRF50'
		   when (model like 'CRF70%')  and make ='HONDA' then 'CRF70'
		   when (model like 'CRF80%')  and make ='HONDA' then 'CRF80'
		   when (model like 'CRV%')  and make ='HONDA' then 'CRV'
		   when (model like 'CT%')  and make ='HONDA' then 'CT'
		   when (model like 'CTX1300%')  and make ='HONDA' then 'CTX1300'
		   when (model like 'CTX700%')  and make ='HONDA' then 'CTX700'
		   when (model like 'CX650%')  and make ='HONDA' then 'CX650'
		   when (model like 'EB10000%')  and make ='HONDA' then 'EB10000'
		   when (model like 'EB2200%')  and make ='HONDA' then 'EB2200'
		   when (model like 'ELEMENT%')  and make ='HONDA' then 'ELEMENT'
		   when (model like 'ELITE%')  and make ='HONDA' then 'ELITE'
		   when (model like 'EM5000%')  and make ='HONDA' then 'EM5000'
		   when (model like 'EM6500%')  and make ='HONDA' then 'EM6500'
		   when (model like 'EU1000%')  and make ='HONDA' then 'EU1000'
		   when (model like 'EU2000%')  and make ='HONDA' then 'EU2000'
		   when (model like 'EU2200%')  and make ='HONDA' then 'EU2200'
		   when (model like 'EU3000%')  and make ='HONDA' then 'EU3000'
		   when (model like 'EU6500%')  and make ='HONDA' then 'EU6500'
		   when (model like 'EU7000%')  and make ='HONDA' then 'EU7000'
		   when (model like 'FOREMAN%')  and make ='HONDA' then 'FOREMAN'
		   when (model like 'FOURTRAX%')  and make ='HONDA' then 'FOURTRAX'
		   when (model like 'FSC600%')  and make ='HONDA' then 'FSC600'
		   when (model like 'GL 1800%')  and make ='HONDA' then 'GL 1800'
		   when (model like 'GL1200%')  and make ='HONDA' then 'GL1200'
		   when (model like 'GL1500%')  and make ='HONDA' then 'GL1500'
		   when (model like 'GL1800%')  and make ='HONDA' then 'GL1800'
		   when (model like 'GL18A%')  and make ='HONDA' then 'GL18A'
		   when (model like 'GL18B%')  and make ='HONDA' then 'GL18B'
		   when (model like 'GL18HP%')  and make ='HONDA' then 'GL18HP'
		   when (model like 'GL18P%')  and make ='HONDA' then 'GL18P'
		   when (model like 'GOLD WING%')  and make ='HONDA' then 'GOLD WING'
		   when (model like 'GROM125%')  and make ='HONDA' then 'GROM125'
		   when (model like 'HRC216%')  and make ='HONDA' then'HRC216'
		   when (model like 'HRN216%')  and make ='HONDA' then 'HRN216'
		   when (model like 'HRR216%')  and make ='HONDA' then 'HRR216'
		   when (model like 'HRX2175%')  and make ='HONDA' then 'HRX2175'
		  when (model like 'INTERSTATE%')  and make ='HONDA' then 'INTERSTATE'
		  when (model like 'MONKEY125%')  and make ='HONDA' then 'MONKEY125'
		  when (model like 'MRT300%')  and make ='HONDA' then 'MRT300'
		  when (model like 'MUV700%')  and make ='HONDA' then 'MUV700'
		  when (model like 'NAVI%')  and make ='HONDA' then 'NAVI'
		  when (model like 'NC700%')  and make ='HONDA' then 'NC700'
		  when (model like 'NC750X%')  and make ='HONDA' then 'NC750X'
		  when (model like 'NCH50%')  and make ='HONDA' then 'NCH50'
		  when (model like 'NCW50%')  and make ='HONDA' then 'NCW50'
		  when (model like 'NHX110%')  and make ='HONDA' then 'NHX110'
		  when (model like 'NIGHT HAWK%')  and make ='HONDA' then 'NIGHT HAWK'
		  when (model like 'NPS50%')  and make ='HONDA' then 'NPS50'
		  when (model like 'NT700%')  and make ='HONDA' then 'NT700'
		  when (model like 'PC800%')  and make ='HONDA' then 'PC800'
		  when (model like 'PCX125%')  and make ='HONDA' then 'PCX125'
		  when (model like 'PCX150%')  and make ='HONDA' then 'PCX150'
		  when (model like 'PIONEER%')  and make ='HONDA' then 'PIONEER'
		  when (model like 'RANCHER%')  and make ='HONDA' then 'RANCHER'
		  when(model like 'REBAL%')  and make ='HONDA' then 'REBAL'
		  when(model like 'REBEL%')  and make ='HONDA' then 'REBEL'
		  when (model like 'RECON%')  and make ='HONDA' then 'RECON'
		  when (model like 'REFLEX%')  and make ='HONDA' then 'REFLEX'
		  when (model like 'SA50%')  and make ='HONDA' then 'SA50'
		  when (model like 'SABRE%')  and make ='HONDA' then 'SABRE'
		  when (model like 'SH150%')  and make ='HONDA' then 'SH150'
		  when (model like 'SHADOW%')  and make ='HONDA' then 'SHADOW'
		  when (model like 'ST1100%')  and make ='HONDA' then 'ST1100'
		  when (model like 'ST13%')  and make ='HONDA' then 'ST13'
		  when (model like 'SXS1000%')  and make ='HONDA' then 'SXS1000'
		  when (model like 'SXS10%')  and make ='HONDA' then 'SXS10'
		  when (model like 'SXS500%')  and make ='HONDA' then 'SXS500'
		  when (model like 'SXS520%')  and make ='HONDA' then 'SXS520'
		  when (model like 'SXS700%')  and make ='HONDA' then 'SXS700'
		  when (model like 'TALON%')  and make ='HONDA' then 'TALON'
		  when (model like 'TRX 350%')  and make ='HONDA' then 'TRX 350'
		  when (model like 'TRX200%')  and make ='HONDA' then 'TRX200'
		  when (model like 'TRX250%')  and make ='HONDA' then 'TRX250'
		  when (model like 'TRX250X%')  and make ='HONDA' then 'TRX250X'
		  when (model like 'TRX300%')  and make ='HONDA' then 'TRX300'
		  when (model like 'TRX300EX%')  and make ='HONDA' then 'TRX300EX'
		  when (model like 'TRX300FW%')  and make ='HONDA' then 'TRX300FW'
		  when (model like 'TRX350%')  and make ='HONDA' then 'TRX350'
		  when (model like 'TRX350FE%')  and make ='HONDA' then 'TRX350FE'
		  when (model like 'TRX350FM%')  and make ='HONDA' then 'TRX350FM'
		  when (model like 'TRX350TE%')  and make ='HONDA' then 'TRX350TE'
		  when (model like 'TRX350TM%')  and make ='HONDA' then 'TRX350TM'
		  when (model like 'TRX400EX%')  and make ='HONDA' then 'TRX400EX'
		  when (model like 'TRX400FA%')  and make ='HONDA' then 'TRX400FA'
		  when (model like 'TRX400FGA%')  and make ='HONDA' then 'TRX400FGA'
		  when (model like 'TRX400FW%')  and make ='HONDA' then 'TRX400FW'
		  when (model like 'TRX400X%')  and make ='HONDA' then 'TRX400X'
		  when (model like 'TRX420%')  and make ='HONDA' then 'TRX420'
		  when (model like 'TRX450ER%')  and make ='HONDA' then 'TRX450ER'
		  when (model like 'TRX450ES%')  and make ='HONDA' then 'TRX450ES'
		  when (model like 'TRX450FE%')  and make ='HONDA' then 'TRX450FE'
		  when (model like 'TRX450FM%')  and make ='HONDA' then 'TRX450FM'
		  when (model like 'TRX450%')  and make ='HONDA' then 'TRX450'
		  when (model like 'TRX500%')  and make ='HONDA' then 'TRX500'
		  when (model like 'TRX520%')  and make ='HONDA' then 'TRX520'
		  when (model like 'TRX650%')  and make ='HONDA' then 'TRX650'
		  when (model like 'TRX680%')  and make ='HONDA' then 'TRX680'
		  when (model like 'TRX70%')  and make ='HONDA' then 'TRX70'
		  when (model like 'TRX90%')  and make ='HONDA' then 'TRX90'
		  when (model like 'VF1100C%')  and make ='HONDA' then 'VF1100C'
		  when (model like 'VF500%')  and make ='HONDA' then 'VF500'
		  when (model like 'VF700%')  and make ='HONDA' then 'VF700'
		  when (model like 'VF750%')  and make ='HONDA' then 'VF750'
	  
		  when (model like 'VFR1200%')  and make ='HONDA' then 'VFR1200'
		  when (model like 'VFR750%')  and make ='HONDA' then 'VFR750'
		  when (model like 'VFR800%')  and make ='HONDA' then 'VFR800'
		  when (model like 'VT100%')  and make ='HONDA' then 'VT100'
		  when (model like 'VT1100%')  and make ='HONDA' then 'VT1100'
		  when (model like 'VT11A1B%')  and make ='HONDA' then 'VT11A1B'
		  when (model like 'VT11B%')  and make ='HONDA' then 'VT11B'
		  when (model like 'VT11C2A%')  and make ='HONDA' then 'VT11C2A'
		  when (model like 'VT1300%')  and make ='HONDA' then 'VT1300'
		  when (model like 'VT13CR%')  and make ='HONDA' then 'VT13CR'
		  when (model like 'VT13CT%')  and make ='HONDA' then 'VT13CT'
		  when (model like 'VT13CX%')  and make ='HONDA' then 'VT13CX'
		  when (model like 'VT1800%')  and make ='HONDA' then 'VT1800'
		  when (model like 'VT500%')  and make ='HONDA' then 'VT500'
		  when (model like 'VT600%')  and make ='HONDA' then 'VT600'
		  when (model like 'VT700%')  and make ='HONDA' then 'VT700'
		  when (model like 'VT750%')  and make ='HONDA' then 'VT750'
		  when (model like 'VT750%')  and make ='HONDA' then 'VT750'
		  when (model like 'VTR1000%')  and make ='HONDA' then 'VTR1000'
		  when (model like 'VTX1300%')  and make ='HONDA' then 'VTX1300'
		  when (model like 'VTX13%')  and make ='HONDA' then 'VTX13'
		  when (model like 'VTX1800%')  and make ='HONDA' then 'VTX1800'
		  when (model like 'VTX18C%')  and make ='HONDA' then 'VTX18C'
		  when (model like 'VTX18%')  and make ='HONDA' then 'VTX18'
		  when (model like 'XR100%')  and make ='HONDA' then 'XR100'
		  when (model like 'XR200%')  and make ='HONDA' then 'XR200'
		  when (model like 'XR250%')  and make ='HONDA' then 'XR250'
		  when (model like 'XR400%')  and make ='HONDA' then 'XR400'
		  when (model like 'XR50%')  and make ='HONDA' then 'XR50'
		  when (model like 'XR600%')  and make ='HONDA' then 'XR600'
		  when (model like 'XR650%')  and make ='HONDA' then 'XR650'
		  when (model like 'XR70%')  and make ='HONDA' then 'XR70'
		  when (model like 'XR80%')  and make ='HONDA' then 'XR80'
		  when (model like 'Z50%')  and make ='HONDA' then 'Z50'
		  when (model like '701%')  and make ='HUSQVARNA' then '701'
		  when (model like 'FE501%')  and make ='HUSQVARNA' then 'FE501'
		  when (model like 'TC 85%')  and make ='HUSQVARNA' then 'TC 85'
		  when (model like 'TE 150%')  and make ='HUSQVARNA' then 'TE 150'
		  when (model like 'TE 250%')  and make ='HUSQVARNA' then 'TE 250'
		  when (model like 'TE300%')  and make ='HUSQVARNA' then 'TE300'
		  when (model like 'VITPILEN%')  and make ='HUSQVARNA' then 'VITPILEN'
		  when (model like 'CHALLENGER%')  and make ='INDIAN' then 'CHALLENGER'
		  when (model like 'CHEIF%')  and make ='INDIAN' then 'CHEIF'
		  when (model like 'CHIEF BOBBER%')  and make ='INDIAN' then 'CHIEF BOBBER'
		  when (model like 'CHIEF VINTAGE%')  and make ='INDIAN' then 'CHIEF VINTAGE'
		  when (model like 'CHIEFTAIN DH%')  and make ='INDIAN' then 'CHIEFTAIN DH'
		  when (model like 'FTR 1200%')  and make ='INDIAN' then 'FTR 1200'
		  when (model like 'N14TCAAA%')  and make ='INDIAN' then 'N14TCAAA'
		  when (model like 'N15CCCAAA%')  and make ='INDIAN' then 'N15CCCAAA'
		  when (model like 'N15CCVAAA%')  and make ='INDIAN' then 'N15CCVAAA'
		  when (model like 'N15TRAAA%')  and make ='INDIAN' then 'N15TRAAA'
		  when (model like 'N16MSB11%')  and make ='INDIAN' then 'N16MSB11'
		  when (model like 'N16THAAA%')  and make ='INDIAN' then 'N16THAAA'
		  when (model like 'N17MSB00%')  and make ='INDIAN' then 'N17MSB00'
		  when (model like 'N18MTB00A%')  and make ='INDIAN' then 'N18MTB00A'
		  when  (model like 'N18TCAAAA%')  and make ='INDIAN' then 'N18TCAAAA'
		  when (model like 'N18TFAAAA%')  and make ='INDIAN' then 'N18TFAAAA'
		  when (model like 'N18TRAAA%')  and make ='INDIAN' then 'N18TRAAA'
		  when (model like 'N19CVAAA%')  and make ='INDIAN' then 'N19CVAAA'
		  when (model like 'N19MSA00%')  and make ='INDIAN' then 'N19MSA00'
		  when (model like 'N19MTA00%')  and make ='INDIAN' then 'N19MTA00'
		  when (model like 'N19TRAAAA%')  and make ='INDIAN' then 'N19TRAAAA'
		  when (model like 'N20LCARRA%')  and make ='INDIAN' then 'N20LCARRA'
		  when (model like 'N21LCBRRA%')  and make ='INDIAN' then 'N21LCBRRA'
		  when (model like 'N21TCDBB%')  and make ='INDIAN' then 'N21TCDBB'
		  when (model like 'N21TJDDB%')  and make ='INDIAN' then 'N21TJDDB'
		  when (model like 'ROADMASTER%')  and make ='INDIAN' then 'ROADMASTER'
		  when (model like 'SCOUT 100%')  and make ='INDIAN' then 'SCOUT 100'
		  when (model like 'SCOUT 60%')  and make ='INDIAN' then 'SCOUT 60'
		  when (model like 'SCOUT ABS%')  and make ='INDIAN' then 'SCOUT ABS'
		  when (model like 'SCOUT BOB%')  and make ='INDIAN' then 'SCOUT BOB'
		  when (model like 'SCOUT BOBBER%')  and make ='INDIAN' then 'SCOUT BOBBER'
		  when (model like 'SCOUT ICON%')  and make ='INDIAN' then 'SCOUT ICON'
		  when (model like 'SCOUT SIXTY%')  and make ='INDIAN' then 'SCOUT SIXTY'
		  when (model like 'SCT BOB 20%')  and make ='INDIAN' then 'SCT BOB 20'
		  when (model like 'SCT BOB 60%')  and make ='INDIAN' then 'SCT BOB 60'
		  when (model like 'SPRINGFIELD%')  and make ='INDIAN' then 'SPRINGFIELD'
		  when (model like 'VINTAGE%')  and make ='INDIAN' then 'VINTAGE'
		WHEN	(model like '1200%' )  and make ='HARLEY-DAVIDSON'			THEN '1200'
		WHEN	(model like '883%' )  and make ='HARLEY-DAVIDSON'			THEN '883'
		WHEN	(model like 'BIG%' )  and make ='HARLEY-DAVIDSON'			THEN 'BIG DOG'
		WHEN	(model like 'BUEL%' )  and make ='HARLEY-DAVIDSON'			THEN 'BUELL'
		WHEN	(model like 'ELEC%' )  and make ='HARLEY-DAVIDSON'			THEN 'ELECTRA GLIDE'
		WHEN	(model like 'ELCTRAGLID%' )  and make ='HARLEY-DAVIDSON'	THEN 'ELECTRA GLIDE'
		WHEN	(model like 'BREAKOUT%' )  and make ='HARLEY-DAVIDSON'		THEN 'BREAKOUT'
		WHEN	(model like 'CUSTOM%' )  and make ='HARLEY-DAVIDSON'		THEN 'CUSTOM'
		WHEN	(model like 'DYAN GLIDE%' )  and make ='HARLEY-DAVIDSON'	THEN 'DYNA GLIDE'
		WHEN	(model like 'DYNA GLUIDE%' )  and make ='HARLEY-DAVIDSON'	THEN 'DYNA GLIDE'
		WHEN	(model like 'DYNO%' )  and make ='HARLEY-DAVIDSON'			THEN 'DYNA'
		WHEN	(model like 'DUECE%' )  and make ='HARLEY-DAVIDSON'			THEN 'DUCE'
		WHEN	(model like 'FLD%103' )  and make ='HARLEY-DAVIDSON'		THEN 'FLD103'
		WHEN	(model like 'FLFBS%' )  and make ='HARLEY-DAVIDSON'			THEN 'FLFBS'
		WHEN	(model like 'FLHPOLICE%' )  and make ='HARLEY-DAVIDSON'		THEN 'FLHP POLICE'
		WHEN	(model like 'FLHRC%' )  and make ='HARLEY-DAVIDSON'			THEN 'FLHRC'
		WHEN	(model like 'FLHR %' )  and make ='HARLEY-DAVIDSON'			THEN 'FLHR SHRINE'
		WHEN	(model like 'FLHTCU-I%' )  and make ='HARLEY-DAVIDSON'		THEN 'FLHTCUI'
		WHEN	(model like 'FLHT...%' )  and make ='HARLEY-DAVIDSON'		THEN 'FLHT'
		WHEN	(model like 'FLHX-103' )  and make ='HARLEY-DAVIDSON'		THEN 'FLHX103'
		WHEN	(model like 'FX SUPERGLIDE' )  and make ='HARLEY-DAVIDSON'	THEN 'FX SUPER GLIDE'
		WHEN	(model like 'FX-1200' )  and make ='HARLEY-DAVIDSON'		THEN 'FX1200'
		WHEN	(model like 'HERATIGE' )  and make ='HARLEY-DAVIDSON'		THEN 'HERITAGE'
		WHEN	(model like 'HERITAGE S%' )  and make ='HARLEY-DAVIDSON'	THEN 'HERITAGE SOFTAIL'
		WHEN	(model like 'HERRITAGE' )  and make ='HARLEY-DAVIDSON'		THEN 'HERITAGE'
		WHEN	(model like 'HERIT SOFT CLAS') and make ='HARLEY-DAVIDSON'	THEN 'HERITAGE'
		WHEN	(model like 'LOWRIDER' )  and make ='HARLEY-DAVIDSON'		THEN 'LOW RIDER'
		WHEN	(model like 'FLSTN 103' )  and make ='HARLEY-DAVIDSON'		THEN 'FLSTN103'
		WHEN	(model like 'IRON 1200™' )  and make ='HARLEY-DAVIDSON'		THEN 'IRONHEAD'
		WHEN	(model like 'FLHTCUSE5-' )  and make ='HARLEY-DAVIDSON'		THEN 'FLHTCUSE5'
		WHEN	(model like 'HER SOFTAIL' )  and make ='HARLEY-DAVIDSON'	THEN 'HERITAGE SOFTAIL'
		WHEN	(model like 'FLHTCUSE5-' )  and make ='HARLEY-DAVIDSON'		THEN 'FLHTCUSE5'
		WHEN	(model like 'FLTRX-103' )  and make ='HARLEY-DAVIDSON'		THEN 'FLTRX103'
		WHEN	(model like 'FXDF FAT' )  and make ='HARLEY-DAVIDSON'		THEN 'FXDF FAT BOB'
		WHEN	(model like 'FXDL DYNA LOW RI') and make ='HARLEY-DAVIDSON'	THEN 'FXDL DYNA LOW RID'
		WHEN	(model like 'MISC.' )  and make ='HARLEY-DAVIDSON'			THEN 'MISC'
		WHEN	(model like 'WIDEGLIDE' )  and make ='HARLEY-DAVIDSON'		THEN 'WIDE GLIDE'
		WHEN	(model like 'FXR-2' )  and make ='HARLEY-DAVIDSON'			THEN 'FXR2'
		WHEN	(model like 'FXDR™ 114' )  and make ='HARLEY-DAVIDSON'		THEN 'FXDR114'
		WHEN	(model like 'FLHTCU%' )  and make ='HARLEY-DAVIDSON'		THEN 'FLHTCU'
		WHEN	(model like 'FLHTK%'  )   and make ='HARLEY-DAVIDSON'		THEN 'FLHTK'
		WHEN	(model like 'FXDWG%' )  and make ='HARLEY-DAVIDSON'			THEN 'FXDWG'
		WHEN	(model like 'FLSTS%' )  and make ='HARLEY-DAVIDSON'			THEN 'FLSTS'
		WHEN	(model like 'FLHRS%' )  and make ='HARLEY-DAVIDSON'			THEN 'FLHRS'
		WHEN	(model like 'FLTRXS%' )  and make ='HARLEY-DAVIDSON'		THEN 'FLTRXS'
		WHEN	(model like 'FXST%' )  and make ='HARLEY-DAVIDSON'			THEN 'FXST'
		WHEN	(model like 'ROADSTER™%' )  and make ='HARLEY-DAVIDSON'		THEN 'ROADSTER'
		WHEN	(model like 'FXR%' )  and make ='HARLEY-DAVIDSON'			THEN 'FXR'
		WHEN	(model like 'FXB%' )  and make ='HARLEY-DAVIDSON'			THEN 'FXB'
		WHEN	(model like 'FXSB%' )  and make ='HARLEY-DAVIDSON'			THEN 'FXSB'
		WHEN	(model like 'MT%' )  and make ='HARLEY-DAVIDSON'			THEN 'MT500'
		WHEN	(model like 'SPORTSTER%' )  and make ='HARLEY-DAVIDSON'		THEN 'SPORTSTER'
		WHEN	(model like 'SOFTAIL%' )  and make ='HARLEY-DAVIDSON'		THEN 'SOFTAIL'
		WHEN	(model like 'SOFT TAIL%' )  and make ='HARLEY-DAVIDSON'		THEN 'SOFTAIL'
		WHEN	(model like 'SHOVELHEAD%' )  and make ='HARLEY-DAVIDSON'	THEN 'SHOVEL HEAD'
		WHEN	(model like 'SPROSTER 1200%' )  and make ='HARLEY-DAVIDSON'	THEN 'SPORTSTER'
		WHEN	(model like 'SUPER GLYDE' )  and make ='HARLEY-DAVIDSON'	THEN 'SUPER GLIDE'
		WHEN	(model like 'SOFTTAIL%' )  and make ='HARLEY-DAVIDSON'		THEN 'SOFTAIL'
		WHEN	(model like 'VRSCAW%' )  and make ='HARLEY-DAVIDSON'		THEN 'VRSCAW'
		WHEN	(model like 'NIGHTTRAI%' )  and make ='HARLEY-DAVIDSON'		THEN 'NIGHT TRAIN'
		WHEN	(model like 'XL1200%' )  and make ='HARLEY-DAVIDSON'		THEN 'XL1200'
		WHEN	(model like 'XL 1200%' )  and make ='HARLEY-DAVIDSON'		THEN 'XL1200'
		WHEN	(model like 'XL883%' )  and make ='HARLEY-DAVIDSON'			THEN 'XL883'
		WHEN	(model like 'XLH 1200%' )  and make ='HARLEY-DAVIDSON'		THEN 'XLH 1200'
		WHEN	(model like 'XR%1200%' )  and make ='HARLEY-DAVIDSON'		THEN 'XR1200'
		WHEN	(model like 'XLH 883%' )  and make ='HARLEY-DAVIDSON'		THEN 'XLH 883'
		WHEN	(model like 'LAZER6021%' )  and make ='SSR'		THEN 'LAZER6021'
		WHEN	(model like 'SR110%' )  and make ='SSR'			THEN 'SR110'
		WHEN	(model like 'SR125%' )  and make ='SSR'			THEN 'SR125'
		WHEN	(model like 'SR140%' )  and make ='SSR'			THEN 'SR140'
		WHEN	(model like 'SR189%' )  and make ='SSR'			THEN 'SR189'
		WHEN	(model like 'SRN%70AUTO%' )  and make ='SSR'	THEN 'SRN070AUTO'
		WHEN	(model like 'SRN%70C%' )  and make ='SSR'		THEN 'SRN070C'
		WHEN	(model like 'SRN110%' )  and make ='SSR'		THEN 'SRN110'
		WHEN	(model like 'SRN125%' )  and make ='SSR'		THEN 'SRN125'
		WHEN	(model like 'SRXF250%' )  and make ='SSR'		THEN 'SRXF250'
		WHEN	(model like 'SSR%' )  and make ='SSR'			THEN 'SSR'
		WHEN	(model like 'SX50%' )  and make ='SSR'			THEN 'SX50'
		WHEN	(model like 'CHALLEN%' )  and make ='SEADOO'	THEN 'CHALLENGER'
		WHEN	(model like 'FISHPRO%' )  and make ='SEADOO'	THEN 'FISHPRO'
		WHEN	(model like 'GTI%' )  and make ='SEADOO'		THEN 'GTI'
		WHEN	(model like 'GTX%' )  and make ='SEADOO'		THEN 'GTX'
		WHEN	(model like 'RTX%' )  and make ='SEADOO'		THEN 'RTX'
		WHEN	(model like 'COMPAGNO%' )  and make ='KYMCO'	THEN 'COMPAGNO'
		WHEN	(model like 'DOWNTOWN%' )  and make ='KYMCO'	THEN 'DOWNTOWN'
		WHEN	(model like 'GRAND%VIST%' )  and make ='KYMCO'	THEN 'GRANDVISTA'
		WHEN	(model like 'KG10%' )  and make ='KYMCO'		THEN 'KG10'
		WHEN	(model like 'KL30SB%' )  and make ='KYMCO'		THEN 'KL30SB'
		WHEN	(model like 'KPIPE%' )  and make ='KYMCO'		THEN 'KPIPE'
		WHEN	(model like 'LA30%' )  and make ='KYMCO'		THEN 'LA30'
		WHEN	(model like 'LB30%' )  and make ='KYMCO'		THEN 'LB30'
		WHEN	(model like 'LIKE%' )  and make ='KYMCO'		THEN 'LIKE'
		WHEN	(model like 'MAXXER%' )  and make ='KYMCO'		THEN 'MAXXER'
		WHEN	(model like 'MONGOOSE%' )  and make ='KYMCO'	THEN 'MONGOOSE'
		WHEN	(model like 'MXU%' )  and make ='KYMCO'			THEN 'MXU'
		WHEN	(model like 'PEOPLE%' )  and make ='KYMCO'		THEN 'PEOPLE'
		WHEN	(model like 'SPADE%' )  and make ='KYMCO'		THEN 'SPADE'
		WHEN	(model like 'SUPER%8%' )  and make ='KYMCO'		THEN 'SUPER 8'
		WHEN	(model like 'UXV%' )  and make ='KYMCO'			THEN 'UXV'
		WHEN	(model like 'X%TOWN%' )  and make ='KYMCO'		THEN 'X TOWN'
		WHEN	(model like 'XCITING%' )  and make ='KYMCO'		THEN 'XCITING'
		WHEN	(model like '%ADVENTURE%' )  and make ='KTM'	THEN 'ADVENTURE'
		WHEN	(model like '%DUKE%' )  and make ='KTM'			THEN 'DUKE'
		WHEN	(model like '%RC390%' )  and make ='KTM'		THEN 'RC390'
		WHEN	(model like '%SX%' )  and make ='KTM'			THEN 'SX'
		WHEN	(model like '%XC%W%' )  and make ='KTM'			THEN 'XCW'
		WHEN	(model like '%MULE%' )  and make ='KAWASAKI'	THEN 'MULE'
		WHEN	(model like '%NINJA%' )  and make ='KAWASAKI'	THEN 'NINJA'
		WHEN	(model like '%PRAIRIE%' )  and make ='KAWASAKI'	THEN 'PRAIRIE'
		WHEN	(model like '%TERYX%' )  and make ='KAWASAKI'	THEN 'TERYX'
		WHEN	(model like '%VERSYS%' )  and make ='KAWASAKI'	THEN 'VERSYS'
		WHEN	(model like '%VN1500%' )  and make ='KAWASAKI'	THEN 'VN1500'
		WHEN	(model like '%VN1600%' )  and make ='KAWASAKI'	THEN 'VN1600'
		WHEN	(model like '%VN1700%' )  and make ='KAWASAKI'	THEN 'VN1700'
		WHEN	(model like '%VN2000%' )  and make ='KAWASAKI'	THEN 'VN2000'
		WHEN	(model like '%VN750%' )  and make ='KAWASAKI'	THEN 'VN750'
		WHEN	(model like '%VN800%' )  and make ='KAWASAKI'	THEN 'VN800'
		WHEN	(model like '%VN900%' )  and make ='KAWASAKI'	THEN 'VN900'
		WHEN	(model like 'Z1000%' )  and make ='KAWASAKI'	THEN 'Z1000'
		WHEN	(model like 'Z400%' )  and make ='KAWASAKI'		THEN 'Z400'
		WHEN	(model like 'Z%650%' )  and make ='KAWASAKI'	THEN 'Z650'
		WHEN	(model like 'ZEPH%' )  and make ='KAWASAKI'		THEN 'ZEPHYER'
		WHEN	(model like 'ZG1000%' )  and make ='KAWASAKI'	THEN 'ZG1000'
		WHEN	(model like 'ZG1200%' )  and make ='KAWASAKI'	THEN 'ZG1200'
		WHEN	(model like 'ZG1400%' )  and make ='KAWASAKI'	THEN 'ZG1400'
		WHEN	(model like 'ZL600%' )  and make ='KAWASAKI'	THEN 'ZL600'
		WHEN	(model like 'ZL900%' )  and make ='KAWASAKI'	THEN 'ZL900'
		WHEN	(model like 'ZR1000%' )  and make ='KAWASAKI'	THEN 'ZR1000'
		WHEN	(model like 'ZR550%' )  and make ='KAWASAKI'	THEN 'ZR550'
		WHEN	(model like 'ZR750%' )  and make ='KAWASAKI'	THEN 'ZR750'
		WHEN	(model like 'ZR800%' )  and make ='KAWASAKI'	THEN 'ZR800'
		WHEN	(model like 'ZR900%' )  and make ='KAWASAKI'	THEN 'ZR900'
		WHEN	(model like 'ZRX%' )  and make ='KAWASAKI'		THEN 'ZRX'
		WHEN	(model like 'ZX%1000%' )  and make ='KAWASAKI'	THEN 'ZX1000'
		WHEN	(model like 'ZX1100%' )  and make ='KAWASAKI'	THEN 'ZX1100'
		WHEN	(model like 'ZX1200%' )  and make ='KAWASAKI'	THEN 'ZX1200'
		WHEN	(model like 'ZX1400%' )  and make ='KAWASAKI'	THEN 'ZX1400'
		WHEN	(model like 'ZX600%' )  and make ='KAWASAKI'	THEN 'ZX600'
		WHEN	(model like 'ZX636%' )  and make ='KAWASAKI'	THEN 'ZX636'
		WHEN	(model like 'ZX750%' )  and make ='KAWASAKI'	THEN 'ZX750'
		WHEN	(model like 'ZX900%' )  and make ='KAWASAKI'	THEN 'ZX900'
		WHEN	(model like 'ZZR600%' )  and make ='KAWASAKI'	THEN 'ZZR600'
		WHEN	(model like 'MEAN STR%' )  and make ='KAWASAKI'	THEN 'MEAN STREAK'
		WHEN	(model like 'BN125%' )  and make ='KAWASAKI'	THEN 'BN125'
		WHEN	(model like 'BR125%' )  and make ='KAWASAKI'	THEN 'BR125'
		WHEN	(model like 'BRUTE%' )  and make ='KAWASAKI'	THEN 'BRUTE'
		WHEN	(model like 'EJ800%' )  and make ='KAWASAKI'	THEN 'EJ800'
		WHEN	(model like 'EN500%' )  and make ='KAWASAKI'	THEN 'EN500'
		WHEN	(model like 'EN650%' )  and make ='KAWASAKI'	THEN 'EN650'
		WHEN	(model like 'ER400%' )  and make ='KAWASAKI'	THEN 'ER400'
		WHEN	(model like 'ER650%' )  and make ='KAWASAKI'	THEN 'ER650'
		WHEN	(model like 'EX250%' )  and make ='KAWASAKI'	THEN 'EX250'
		WHEN	(model like 'EX300%' )  and make ='KAWASAKI'	THEN 'EX300'
		WHEN	(model like 'EX400%' )  and make ='KAWASAKI'	THEN 'EX400'
		WHEN	(model like 'EX500%' )  and make ='KAWASAKI'	THEN 'EX500'
		WHEN	(model like 'EX650%' )  and make ='KAWASAKI'	THEN 'EX650'
		WHEN	(model like 'KAF1000%' )  and make ='KAWASAKI'	THEN 'KAF1000'
		WHEN	(model like 'KAF300%' )  and make ='KAWASAKI'	THEN 'KAF300'
		WHEN	(model like 'KAF400%' )  and make ='KAWASAKI'	THEN 'KAF400'
		WHEN	(model like 'KAF620%' )  and make ='KAWASAKI'	THEN 'KAF620'
		WHEN	(model like 'KAF700%' )  and make ='KAWASAKI'	THEN 'KAF700'
		WHEN	(model like 'KAF820%' )  and make ='KAWASAKI'	THEN 'KAF820'
		WHEN	(model like 'KAF950%' )  and make ='KAWASAKI'	THEN 'KAF950'
		WHEN	(model like 'KAT820%' )  and make ='KAWASAKI'	THEN 'KAT820'
		WHEN	(model like 'KDX%200%' )  and make ='KAWASAKI'	THEN 'KDX200'
		WHEN	(model like 'KDX50%' )  and make ='KAWASAKI'	THEN 'KDX50'
		WHEN	(model like 'KF950%' )  and make ='KAWASAKI'	THEN 'KF950'
		WHEN	(model like 'KL650%' )  and make ='KAWASAKI'	THEN 'KL650'
		WHEN	(model like 'KLE300%' )  and make ='KAWASAKI'	THEN 'KLE300'
		WHEN	(model like 'KLE650%' )  and make ='KAWASAKI'	THEN 'KLE650'
		WHEN	(model like 'KLF%220%' )  and make ='KAWASAKI'	THEN 'KLF220'
		WHEN	(model like 'KLF250%' )  and make ='KAWASAKI'	THEN 'KLF250'
		WHEN	(model like 'KLF300%' )  and make ='KAWASAKI'	THEN 'KLF300'
		WHEN	(model like 'KLR%250%' )  and make ='KAWASAKI'	THEN 'KLR250'
		WHEN	(model like 'KLR%650%' )  and make ='KAWASAKI'	THEN 'KLR650'
		WHEN	(model like 'KLX%110%' )  and make ='KAWASAKI'	THEN 'KLX110'
		WHEN	(model like 'KLX125%' )  and make ='KAWASAKI'	THEN 'KLX125'
		WHEN	(model like 'KLX140%' )  and make ='KAWASAKI'	THEN 'KLX140'
		WHEN	(model like 'KLX200%' )  and make ='KAWASAKI'	THEN 'KLX200'
		WHEN	(model like 'KLX230%' )  and make ='KAWASAKI'	THEN 'KLX230'
		WHEN	(model like 'KLX250%' )  and make ='KAWASAKI'	THEN 'KLX250'
		WHEN	(model like 'KLX300%' )  and make ='KAWASAKI'	THEN 'KLX300'
		WHEN	(model like 'KLZ1000%' )  and make ='KAWASAKI'	THEN 'KLZ1000'
		WHEN	(model like 'KRF1000%' )  and make ='KAWASAKI'	THEN 'KRF1000'
		WHEN	(model like 'KRF750%' )  and make ='KAWASAKI'	THEN 'KRF750'
		WHEN	(model like 'KRF800%' )  and make ='KAWASAKI'	THEN 'KRF800'
		WHEN	(model like 'KRT750%' )  and make ='KAWASAKI'	THEN 'KRT750'
		WHEN	(model like 'KRT800%' )  and make ='KAWASAKI'	THEN 'KRT800'
		WHEN	(model like 'KRX1000%' )  and make ='KAWASAKI'	THEN 'KRX1000'
		WHEN	(model like 'KSF400%' )  and make ='KAWASAKI'	THEN 'KSF400'
		WHEN	(model like 'KSF450%' )  and make ='KAWASAKI'	THEN 'KSF450'
		WHEN	(model like 'KSF50%' )  and make ='KAWASAKI'	THEN 'KSF50'
		WHEN	(model like 'KSF90%' )  and make ='KAWASAKI'	THEN 'KSF90'
		WHEN	(model like 'KSV700%' )  and make ='KAWASAKI'	THEN 'KSV700'
		WHEN	(model like 'KVF300%' )  and make ='KAWASAKI'	THEN 'KVF300'
		WHEN	(model like 'KVF360%' )  and make ='KAWASAKI'	THEN 'KVF360'
		WHEN	(model like 'KVF400%' )  and make ='KAWASAKI'	THEN 'KVF400'
		WHEN	(model like 'KVF650%' )  and make ='KAWASAKI'	THEN 'KVF650'
		WHEN	(model like 'KVF700%' )  and make ='KAWASAKI'	THEN 'KVF700'
		WHEN	(model like 'KVF750%' )  and make ='KAWASAKI'	THEN 'KVF750'
		WHEN	(model like 'KX%100%' )  and make ='KAWASAKI'	THEN 'KX100'
		WHEN	(model like 'KX250%' )  and make ='KAWASAKI'	THEN 'KX250'
		WHEN	(model like 'KX252%' )  and make ='KAWASAKI'	THEN 'KX252'
		WHEN	(model like 'KX450%' )  and make ='KAWASAKI'	THEN 'KX450'
		WHEN	(model like 'KX65%' )  and make ='KAWASAKI'		THEN 'KX65'
		WHEN	(model like 'KX80%' )  and make ='KAWASAKI'		THEN 'KX80'
		WHEN	(model like 'KX85%' )  and make ='KAWASAKI'		THEN 'KX85'
		WHEN	(model like 'KZ1000%' )  and make ='KAWASAKI'	THEN 'KZ1000'
		WHEN	(model like 'KZ550%' )  and make ='KAWASAKI'	THEN 'KZ550'
		WHEN	(model like 'LAKOTA%' )  and make ='KAWASAKI'	THEN 'LAKOTA'
		when	(model like 'AN400%' )  and make ='SUZUKI'	then	'AN400'
		when	(model like 'AN650%' )  and make ='SUZUKI'	then	'AN650'
		when	(model like 'BANDIT%' )  and make ='SUZUKI'	then	'BANDIT'
		when	(model like 'BLVD%' )  and make ='SUZUKI'	then	'BLVD'
		when	(model like 'BOLUEVARD%' or model like 'BOULEVARD%')  and make ='SUZUKI' then 'BOULEVARD'
		when	(model like 'BURGMAN%650%' )  and make ='SUZUKI'		then	'BURGMAN650'
		WHEN	(model like 'BUS%' )  and make ='SUZUKI'		THEN	'BUSA'
		WHEN	(model like 'C%90%' )  and make ='SUZUKI'		THEN	'C90'
		WHEN	(model like 'C%50%' )  and make ='SUZUKI'		THEN	'C50'
		WHEN	(model like 'DL%1000%' )  and make ='SUZUKI'	THEN	'DL1000'
		WHEN	(model like 'DL%650%' )  and make ='SUZUKI'		THEN	'DL650'
		WHEN	(model like 'DR%Z%' )  and make ='SUZUKI'		THEN	'DRZ'
		WHEN	(model like 'DR%200%' )  and make ='SUZUKI'		THEN	'DR200'
		WHEN	(model like 'DR%350%' )  and make ='SUZUKI'		THEN	'DR350'
		WHEN	(model like 'DR%650%' )  and make ='SUZUKI'		THEN	'DR650'
		WHEN	(model like 'EIGER%' )  and make ='SUZUKI'		THEN	'EIGER'
		WHEN	(model like 'GS500%' )  and make ='SUZUKI'		THEN	'GS500'
		WHEN	(model like 'GSF%' )  and make ='SUZUKI'		THEN	'GSF'
		WHEN	(model like 'GSX%' )  and make ='SUZUKI'		THEN	'GSX'
		WHEN	(model like 'GZ%250%' )  and make ='SUZUKI'		THEN	'GZ250'
		WHEN	(model like 'INTRU%' )  and make ='SUZUKI'		THEN	'INTRUDER'
		WHEN	(model like 'JR50%' )  and make ='SUZUKI'		THEN	'JR50'
		WHEN	(model like 'KING%QUAD%' )  and make ='SUZUKI'	THEN	'KINGQUAD'
		WHEN	(model like 'LS650%' )  and make ='SUZUKI'		THEN	'LS650'
		WHEN	(model like 'LT%160%' )  and make ='SUZUKI'		THEN	'LT160'
		WHEN	(model like 'LT%A%' )  and make ='SUZUKI'		THEN	'LTA'
		WHEN	(model like 'LT%F%' )  and make ='SUZUKI'		THEN	'LTF'
		WHEN	(model like 'LT%R%' )  and make ='SUZUKI'		THEN	'LTR'
		WHEN	(model like 'LT%Z%' )  and make ='SUZUKI'		THEN	'LTZ'
		WHEN	(model like 'LT%250%' )  and make ='SUZUKI'		THEN	'LT250'
		WHEN	(model like 'LT80%' )  and make ='SUZUKI'		THEN	'LT80'
		WHEN	(model like 'M109%' )  and make ='SUZUKI'		THEN	'M109'
		WHEN	(model like 'M50%' )  and make ='SUZUKI'		THEN	'M50'
		WHEN	(model like 'M90%' )  and make ='SUZUKI'		THEN	'M90'
		WHEN	(model like 'OZARK%' )  and make ='SUZUKI'		THEN	'OZARK'
		WHEN	(model like 'RM%Z%' )  and make ='SUZUKI'		THEN	'RMZ'
		WHEN	(model like 'RM%125%' )  and make ='SUZUKI'		THEN	'RM125'
		WHEN	(model like 'RM250%' )  and make ='SUZUKI'		THEN	'RM250'
		WHEN	(model like 'RM80%' )  and make ='SUZUKI'		THEN	'RM80'
		WHEN	(model like 'RM85%' )  and make ='SUZUKI'		THEN	'RM85'
		WHEN	(model like 'RMX%' )  and make ='SUZUKI'		THEN	'RMX'
		WHEN	(model like 'S40%' )  and make ='SUZUKI'		THEN	'S40'
		WHEN	(model like 'S50%' )  and make ='SUZUKI'		THEN	'S50'
		WHEN	(model like 'S83%' )  and make ='SUZUKI'		THEN	'S83'
		WHEN	(model like 'SAVAGE%' )  and make ='SUZUKI'		THEN	'SAVAGE'
		WHEN	(model like 'SFV650%' )  and make ='SUZUKI'		THEN	'SFV650'
		WHEN	(model like 'SV%650%' )  and make ='SUZUKI'		THEN	'SV650'
		WHEN	(model like 'SV1000%' )  and make ='SUZUKI'		THEN	'SV1000'
		WHEN	(model like 'TL%1000%' )  and make ='SUZUKI'	THEN		'TL1000'
		WHEN	(model like 'UH200%' )  and make ='SUZUKI'		THEN	'UH200'
		WHEN	(model like 'VL1500%' )  and make ='SUZUKI'		THEN	'VL1500'
		WHEN	(model like 'VL800%' )  and make ='SUZUKI'		THEN	'VL800'
		WHEN	(model like 'VZ1500%' )  and make ='SUZUKI'		THEN	'VZ1500'
		WHEN	(model like 'VZ1800%' )  and make ='SUZUKI'		THEN	'VZ1800'
		WHEN	(model like 'VZ800%' )  and make ='SUZUKI'		THEN	'VZ800'
		WHEN	(model like 'VZR%' )  and make ='SUZUKI'		THEN	'VZR'
		WHEN	(model like 'Xl%7%%' )  and make ='SUZUKI'		THEN	'XL7'
		when	(model like '%RAW%' )  and make ='TIMBERSLED'	then	'RAW'
		when	(model like 'ST%120%' )  and make ='TIMBERSLED'	then	'ST120'
		when (model like 'AMERICA%' )  and make ='TRIUMPH'		then 'AMERICAN'
		when (model like 'BONN%' )  and make ='TRIUMPH'			then 'BONNEVILLE'
		when (model like 'DAYTONA%' )  and make ='TRIUMPH'		then 'DAYTONA'
		when (model like 'ROCKET%' )  and make ='TRIUMPH'		then 'ROCKET'
		when (model like 'SCRAMBLER%' )  and make ='TRIUMPH'	then 	'SCRAMBLER'
		when (model like 'SPEED%' )  and make ='TRIUMPH'		then 	'SPEED'
		when (model like 'SPRINT%' )  and make ='TRIUMPH'		then 'SPRINT'
		when (model like 'T%100%' )  and make ='TRIUMPH'		then 	'T100'
		when (model like 'THRUXTON%' )  and make ='TRIUMPH'		then 'THRUXTON'
		when (model like 'THUNDERBIRD%' )  and make ='TRIUMPH'	then 	'THUNDERBIRD'
		when (model like 'TIGER%' )  and make ='TRIUMPH'		then 	'TIGER'
		when (model like 'TRIDENT%' )  and make ='TRIUMPH'		then 'TRIDENT'
		----------
		when (model like '%MOUNTAINMAX%' )  and make ='YAMAHA'	THEN	'MOUNTAINMAX'
		when (model like '%Sportsman%' )  and make ='YAMAHA'		THEN	'SPORTSMAN'
		when (model like '%RAPTOR%' )  and make ='YAMAHA'		THEN	'RAPTOR'
		when (model like '%APEX%' )  and make ='YAMAHA'			THEN	'APEX'
		when (model like '%BEAR TRAKER%' )  and make ='YAMAHA'	THEN	'BEAR TRACKER'
		when (model like '%BOLT%' )  and make ='YAMAHA'			THEN	'BOLT'
		when (model like '%CP250%' )  and make ='YAMAHA'			THEN	'CP250'
		when (model like '%CW50%' )  and make ='YAMAHA'			THEN	'CW50'
		when (model like '%CZD300%' )  and make ='YAMAHA'		THEN	'CZD300'
		when (model like '%EF%' )  and make ='YAMAHA'			THEN	'EF'
		when (model like 'ER%' )  and make ='YAMAHA'				THEN	'ER'
		when (model like 'EX%' )  and make ='YAMAHA'				THEN	'EX'
		when (model like 'FA%1800%' )  and make ='YAMAHA'		THEN	'FA1800'
		when (model like 'FB%1800%')  and make ='YAMAHA'			THEN	'FB1800'
		when (model like 'FC%1800%')  and make ='YAMAHA'			THEN	'FC1800'
		when (model like 'FJ%9%' )  and make ='YAMAHA'			THEN	'FJ09'
		when (model like 'FJR%' )  and	make ='YAMAHA'			THEN	'FJR'
		when (model like 'FX%' )  and		make ='YAMAHA'				THEN	'FX'
		when (model like 'FZ%6%' )  and	make ='YAMAHA'			THEN	'FZ 6'
		when (model like 'FZ%10%' )  and	make ='YAMAHA'			THEN	'FZ 10'
		when (model like 'GENERATOR%' )  and make ='YAMAHA'		THEN	'GENERATOR'	
		when (model like 'JY44%' )  and	make ='YAMAHA'			THEN	'JY44'
		when (model like 'MT%03%' )  and	make ='YAMAHA'			THEN	'MT 03'
		when (model like 'MT%07%' )  and	make ='YAMAHA'			THEN	'MT 07'
		when (model like 'MT%09%' )  and	make ='YAMAHA'			THEN	'MT 09'
		when (model like 'MTT9%' )  and	make ='YAMAHA'			THEN	'MTT9'
		when (model like 'NYTRO%' )  and	make ='YAMAHA'			THEN	'NYTRO'
		when (model like 'OTHER%' )  and	make ='YAMAHA'			THEN	'OTHER'
		when (model like 'PW%50%' )  and	make ='YAMAHA'			THEN	'PW50'
		when (model like 'PW3028%' )  and make ='YAMAHA'			THEN	'PW3028'
		when (model like 'PZ480%' )  and	make ='YAMAHA'			THEN	'PZ480'
		when (model like 'R-1%' )  and	make ='YAMAHA'			THEN	'R1'
		when (model like 'R6%' )  and		make ='YAMAHA'				THEN	'R6'
		when (model like 'SCR95%' )  and	make ='YAMAHA'			THEN	'SCR95'
		when (model like 'SECA%' )  and	make ='YAMAHA'			THEN	'SECA'
		when (model like 'SJ700%' )  and	make ='YAMAHA'			THEN	'SJ700'
		when (model like 'SR%400%' )  and make ='YAMAHA'			THEN	'SR400'
		when (model like 'SRX%' )  and	make ='YAMAHA'			THEN	'SRX'
		when (model like 'TT%R%' )  and	make ='YAMAHA'			THEN	'TTR'
		when (model like 'TW200%' )  and	make ='YAMAHA'			THEN	'TW200'
		when (model like 'XP500%' )  and	make ='YAMAHA'			THEN	'XP500'
		when model like 'fatboy%' then 'Fat Boy' 
		when (model like '%road star%'or model like '%roadstar%') then 'ROAD STAR' 
		when (model like '%roadking%'or model like'%road king%') then 'ROAD KING' 
		when (model like '%WAVERUNNER%' or model like '%WAVE RUNNER%') then 'WAVE RUNNER' 
		when model like '#%' then substring(model,2,len(model)-1)
		when (model like '883 SPORTSTER') then 'SPORTSTER 883'
		when (model like '0') then 'Unknown'
		when (model like '1190 ADV R') then '1190 ADVENTURE'
		when (model like 'ADVENTURER') then 'ADVENTURE'
		when (model like '1199 PANIGALE%') then 'PANIGALE 1199'
		when (model like '%//%') then substring(model,1,charindex('//',model)-1)
		when (model like 'N/A') then 'Unknown'
		when (model like '%/%') then substring(model,1,charindex('/',model)-1)
		when (model like '%(%') then substring(model,1,charindex('(',model)-1)
		when (model like '%883%SPORTSTER') then 'SPORTSTER 883'
		when (model like 'SPRTSTER%883') then 'SPORTSTER 883'
		when (model like '%1200%SPORTSTER%') then 'SPORTSTER 1200'
		when (model like 'XL883')  then 'XL 883'
		when (model like 'XLH883')  then 'XLH 883'
		when model like '%AGILITY%50%' then 'AGILITY 50'
		when model like '%AGILITY%125%' then 'AGILITY 125'
		when (model like '%SPORTSMAN%90%' or model like '%90%SPORTSMAN%') then 'SPORTSMAN 90'
		when (model like '%SPORTSMAN%570%' or model like '%570%SPORTSMAN%') then 'SPORTSMAN 570'
		when (model like '%SPORTSMAN%500%' or model like '%500%SPORTSMAN%') then 'SPORTSMAN 500'
		when (model like '%SPORTSMAN%335%' or model like '%335%SPORTSMAN%') then 'SPORTSMAN 335'
		when (model like '%SPORTSMAN%400%' or model like '%400%SPORTSMAN%') then 'SPORTSMAN 400'
		when (model like '%SPORTSMAN%450%' or model like '%450%SPORTSMAN%') then 'SPORTSMAN 450'
		when (model like '%SPORTSMAN%550%' or model like '%550%SPORTSMAN%') then 'SPORTSMAN 550'
		when (model like '%SPORTSMAN%700%' or model like '%700%SPORTSMAN%') then 'SPORTSMAN 700'
		when (model like '%SPORTSMAN%800%' or model like '%800%SPORTSMAN%') then 'SPORTSMAN 800'
		when (model like '%SPORTSMAN%850%' or model like '%850%SPORTSMAN%') then 'SPORTSMAN 850'
		when (model like '%50 PREDATOR%' or  model like '%PREDATOR%50' or  model like '%50 PRED%'or  model like '%PRED%50')	then 'PREDATOR 50'
		when (model like '%90 PREDATOR%' or  model like '%PREDATOR%90' or  model like '%90 PRED%'or  model like '%PRED%90')	then 'PREDATOR 90'
		when (model like '%500 PREDATOR%' or model like '%PREDATOR%500' or model like '%500 PRED%'or model like '%PRED%500')	then 'PREDATOR 500'
		when (model like '%VINSON%') then 'VINSON 500'
		when (model like 'VMAX%' or model like 'V MAX%') then 'V MAX'
		when (model like '%350%BANSHEE%' or model like '%BANshee%350%') then 'BANSHEE 350'
		when (model like '%ROYAL STAR%' or  model like '%ROYALSTAR%')   then 'ROYAL STAR'
		when model like '1200XLT'	  then '1200 XLT'
		when model like '212X'		  then '212 X'
		when model like '%242%'		  then '242 LIMITED'
		when model like '25o%'		  then '250'
		when model like '%BEARTRACKE%' then 'BEAR TRACKER'
		when (model like '%350%BRUIN%' or   model like '%BRUIN%350%' )	then 'BRUIN 350'
		when (model like '%350%RAPTOR%' or  model like '%RAPTOR%350%' )	then 'RAPTOR 350'
		when (model like '%400%KODIAK%' or  model like '%KODIAK%400%' )	then 'KODIAK 400'
		when (model like '%450%Kodiak%' or  model like '%Kodiak%450%' )	then 'KODIAK 450'
		when (model like '%450%Rhino%' or   model like '%Rhino%450%' )	then 'RHINO 450'
		when (model like '%660%RHINO%' or   model like '%RHINO%660%' )	then 'RHINO 660'
		when (model like '%700%KODIAK%' or  model like '%KODIAK%700%' )	then 'KODIAK 700'
		when (model like '%700%RAPTO%' or   model like '%RAPTO%700%' )	then 'RAPTOR 700'
		when (model like '%700%RHINO%' or   model like '%RHINO%700%' )	then 'RHINO 700'
		when (model like '%750%SEC%' or     model like '%SEC%750%' )		then '750 SPECIAL'
		when (model like '%750%SPECIA%' or  model like '%SPECIA%750%' )	then '750 SPECIAL'
		when (model like '%AR%230%' or		model like '%230%ar%' )		then 'AR 230'
		when (model like '%AR%240%' or		model like '%240%ar%' )		then 'AR 240'
		when (model like '%AR%210%' or		model like '%210%ar%' )		then 'AR 210'
		when (model like '%BIG%BEAR%350%'or model like '%350%BIG%BEAR%' )	then 'BIG BEAR 350'
		when (model like '%BIG%BEAR%400%' or model like '%400%BIG%BEAR%' )then 'BIG BEAR 400'
		when (model like 'BIG%BEAR' or	     model like 'BIG%BEAR' )		then 'BIG BEAR'
		when (model like '%Breeze%' )  and make ='YAMAHA'				then 'BREEZE'
		when (model like '%BLASTER%' )  and make ='YAMAHA'			then 'BLASTER'
		when (model like '%DT%250%' or	     model like '%250%DT%' )      then 'DT 250'
		when model like '%FX%CRU%' then 'FX CRUISER'
		when model like '%FX%SHO%' then 'FX CRUISER'
		when (model like 'FZ%10' or model like '10%FZ' )	then 'FZ 10'
		when (model like 'FZ%6'or	model like '6%FZ' )	then 'FZ 6'
		when (model like 'FZ%8%'or	model like '8%FZ' )	then 'FZ 8'
		when (model like 'FZ%1'or	model like '1%FZ' )	then 'FZ 1'
		when (model like 'FZ%7%'or	model like '7%FZ%' )	then 'FZ 7'
		when (model like 'FZ%9%'or	model like '9%FZ%' )	then 'FZ 9'
		when model like '%FZR%'			then 'FZR'
		when model like '%FZS%'			then 'FZS'
		when (model like '%GP%1200%' or	model like '%1200%GP%')	then 'GP 1200'
		when (model like '%GP%1300%' or	model like '%1300%GP%')	then 'GP 1300'
		when (model like '%GP%800%' or	model like '%800%GP%')	then 'GP 800'
		when (model like '%GP%1800%' or	model like '%1800%GP%')	then 'GP 1800'
		when (model like '%GP%760%' or	model like '%760%GP%')	then 'GP 760'
		when (model like '%GRIZZLEY%'	)								then 'GRIZZLY'
		when (model like '%GRIZZL%' )  and make ='YAMAHA'			then 'GRIZZLY'
		when (model like '%GT%80%' or		model like '%80%GT%')		then 'GT 80'
		when (model like '%GTS%1000%' or	model like '%1000%GTS%')	then 'GTS 1000'
		when (model like '%GX%1800%' or	model like '%1800%GX%')	then 'GX 1800'
		when (model like '%EX%1050%' or	model like '%1050%EX%')	then 'EX 1050'
		when (model like '%FA%1800%' or	model like '%1800%FA%')	then 'FA 1800'
		when (model like '%FB%1800%' or	model like '%1800%FB%')	then 'FB 1800'
		when (model like '%FC%1800%' or	model like '%1800%FC%')	then 'FC 1800'
		when (model like '%FJ%09%' or		model like '%09%FJ%')		then 'FJ 09'
		when (model like '%FJ1200%' or	model like '%1200FJ%')	then 'FJ 1200'
		when (model like '%FJR%1300%' or	model like '%1300%FJR%')	then 'FJR 1300'
		when (model like '%FJR%13%' and	model not like '%FJR%1300%') then 'FJR 13'
		when (model like '%FX%1000%' )	then 'FX 1000'
		when (model like '%FX%1100%' )	then 'FX 1100'
		when (model like '%FX%10M%' )		then 'FX 10M'
		when (model like '%FX%1800%' )	then 'FX 1800'
		when (model like '%FY%1800%' )	then 'FX 1800'
		when (model like '%LS%2000%' )	then 'LS 2000'
		when (model like '%MAJESTY%400%' )	then	'MAJESTY 400'
		when (model like '%MAXI%550%' )	then 'MAXIM 550'
		when (model like '%MAXI%650%' )	then 'MAXIM 650'
		when (model like '%MAXI%750%' )	then 'MAXIM 750'
		when (model like 'MAXIUM' )		then 'MAXIM'
		when (model like 'MM700%')		then 'MM700'
		when (model like 'MOTO%4%')		then 'MOTO 4'
		when (model like 'MT%07%' )		then 'MT 07'
		when (model like 'MT%09%' )		then 'MT 09'
		when (model like 'MT%03%' )		then 'MT 03'
		when (model like 'MT10%')			then 'MT 10'
		when (model like 'MTT9%' )		then 'MTT9'
		when (model like '%NYTRO%' )  and make ='YAMAHA' then 'NYTRO'
		when (model like 'PW%50%' )		then 'PW50'
		when (model like 'PW%80%' )		then 'PW80'
		when (model like 'PW%3028%' )		then 'PW3028'
		when (model like 'PW%4040%' )		then 'PW4040'
		when (model like 'PZ%480%' )		then	'PZ480'
		when (model like 'PZ%50%' )		then	'PZ50'
		when (model like 'R-3' )			then	'R3'
		when (model like 'R-6%' OR model like 'R6S' OR model like 'R6 S')	then	'R6'
		when (model like 'RAIDER XV19%' )	then	'RAIDER XV19'
		when (model like 'RAODSTAR1600' )	then	'ROADSTAR1600'
		when (model like 'RAPTER%' OR model like 'REPTOR%') then 'RAPTOR'
		when (model like 'RAPTOR50')	then	'RAPTOR 50'
		when (model like 'RAPTOR90%' OR model like 'RAPTOR 90%')	then	'RAPTOR 90'
		when (model like 'REVA' )	then	'RIVA'
		when (model like 'ROAD%LINER%' )	then 'ROADLINER'
		when (model like 'RS90%' )	then	'RS90'
		when (model like 'RSG90%' )	then	'RSG90'
		when (model like 'RS%VECTOR%' )	then	'RSVECTOR'
		when (model like 'rs%venture%' )		then 'RS VENTURE'
		when (model like 'RX-1' OR model like 'RX1 WA%')	then	'RX1'
		when (model like 'RX10%' )	then		'RX10'
		when (model like 'RXW10%' )	then		'RXW10'
		when (model like 'RYAL%STAR%' OR model like 'RYL%STAR%')	then	'ROYAL STAR'
		when (model like 'SECA II' )		then 'SECA 2'
		when (model like 'SIDEWINDE%' )	then 'SIDEWINDER'
		when (model like 'SILERADO%' )	then 'SILVERADO'
		when (model like 'SJ700%' )		then 'SJ700'
		when (model like 'Sno%Scoot%' )	then 'SNOSCOOT'
		when (model like 'SR400%' )		then 'SR 400'
		when (model like 'SR10%' )		then 'SR10'
		when (model like 'SRVIPER%' )	then 'SRVIPER'
		when (model like 'STRATO%' )	then 	'STRATOLINER'
		when (model like 'SUPER' OR model like 'SUPERTENE%' OR model like 'SUPER TENE%' )	then'SUPER TENERE'
		when (model like 'SUPERJET%' OR model like 'SUPER JET%'OR model like 'SUPERES')	then	'SUPER JET'
		when (model like '%snoscoot%' )  and make ='YAMAHA' then 'SNOSCOOT'
		when (model like 'SW10%' )	then 	'SW10'
		when (model like 'SW1NMS%' )	then 	'SW1NMS'
		when (model like 'SX 230%' )	then 	'SX230'
		when (model like 'SXR%' )		then 'SXR'
		when (model like 'SXV%700%' )	then 'SXV700'
		when (model like 'TIMBERWOLF%' OR model like'TMBRWLF%')	then	'TIMBERWOLF'
		when (model like 'Tracer%900%GT%' )	then	'TRACER900GT'
		when (model like 'TW%200%' )		then	'TW200'
		when (model like 'U' or model like 'UNKNOWN')	then 'UNKNOWN MODEL'
		when (model like 'V%MAX%' )	then	'V MAX'
		when (model like '%V%STAR%' )	then 'V STAR'
		when (model like '%V1 SPORT%' )	then 'V1 SPORT'
		when (model like '%VC%1800%' )	then 'VC1800'
		when (model like 'VENTURE%' )	then 'VENTURE'
		when (model like '%VIKING%' )	then 'VIKING'
		when (model like '%VINO%' )	then	'VINO'
		when (model like '%VIPER%' ) and make ='YAMAHA' then 'VIPER'
		when (model like '%VIRAGO%' )	then 'VIRAGO'
		when (model like '%VK10%' )	then 	'VK10'
		when (model like '%VMX%' )	then 	'VMX'
		when (model like 'VS%' )		then 	'VS'
		when (model like 'VT%' )  and make ='YAMAHA'	then 'VT'
		when (model like '%Vulcan%' )	then 'VULCAN'
		when (model like '%VX%' )  and make ='YAMAHA' then 'VX'
		when (model like '%WARRIOR%' )	then 'WARRIOR'
		when (model like '%WAVE%BLASTER%' )	then 'WAVE BLASTER'
		when (model like '%WAVE%RAIDER%' )	then 'WAVE RAIDER'
		when (model like '%WAVE%RUNNER%' )	then 'WAVE RUNNER'
		when (model like '%WAVE%VENTURE%' )	then 'WAVE VENTURE'
		when (model like '%WBASH%' )			then 'WBASH'
		when (model like '%WOLVERIN%' )		then 'WOLVERINE'
		when (model like '%WR%' )  and make ='YAMAHA'	then 'WR'
		when (model like '%XA%' )  and make ='YAMAHA'	then 'XA'
		when (model like '%XC%' )  and make ='YAMAHA'	then 'XC'
		when (model like '%XF%' )  and make ='YAMAHA'	then 'XF'
		when (model like '%XJ%' )  and make ='YAMAHA'	then 'XJ'
		when (model like '%XL%' )  and make ='YAMAHA'	then 'XL'
		when (model like '%XS%' )  and make ='YAMAHA'	then 'XS'
		when (model like '%XT%' )  and make ='YAMAHA'	then 'XT'
		when (model like '%XV%' )  and make ='YAMAHA'	then 'XV'
		when (model like '%YFA%' )  and make ='YAMAHA'	then 'YFA'
		when (model like '%YFB%' )  and make ='YAMAHA'	then 'YFB'
		when (model like '%YFH%' )  and make ='YAMAHA'	then 'YFH'
		when (model like '%YFM%' )  and make ='YAMAHA'	then 'YFM'
		when (model like '%YFP%' )  and make ='YAMAHA'	then 'YFP'
		when (model like '%YFS%' )  and make ='YAMAHA'	then 'YFS'
		when (model like '%YFZ%' )  and make ='YAMAHA'	then 'YFZ'
		when (model like '%YJ%' )  and make ='YAMAHA'	then 'YJ'
		when (model like '%YM%' )  and make ='YAMAHA'	then 'YM'
		when (model like '%YP%' )  and make ='YAMAHA'	then 'YP'
		when (model like '%YRM%' )  and make ='YAMAHA'	then 'YRM'
		when (model like '%YTORC%' )  and make ='YAMAHA'then 'YTORC'
		when (model like '%YW%' )  and make ='YAMAHA'	then 'YW'
		when (model like '%YXC%' )  and make ='YAMAHA'	then 'YXC'
		when (model like '%YXE%' )  and make ='YAMAHA'	then 'YXE'
		when (model like '%YXF%' )  and make ='YAMAHA'	then 'YXF'
		when (model like '%YXM%' )  and make ='YAMAHA'	then 'YXM'
		when (model like '%YXP%' )  and make ='YAMAHA'	then 'YXP'
		when (model like '%YXR%' )  and make ='YAMAHA'	then 'YXR'
		when (model like '%YXZ%' )  and make ='YAMAHA'	then 'YXZ'
		when (model like '%YZ%' )  and make ='YAMAHA'	then 'YZ'
		when (model like '%ZUMA%' )  and make ='YAMAHA'	then 'ZUMA'
		when (model like '%TTR%' )  and  make ='YAMAHA' THEN 'TTR'
		when (model like '%FZ%07%' )  and make ='YAMAHA' then 'FZ 7'
		else model end ),
		modelyear = (case when len(isnull(modelyear,''))<4 then 1900 else modelyear end)

	--Inserting new Make,Model,Year vehicle data  to master.vehicle_makemodel 

	insert into clictell_auto_master.master.vehicle_makemodel 
	(
		make
		,makedesc
		,model
		,modeldesc
		,modelyear
		,vertical_id
		,created_by
		,created_dt
		,updated_by
		,updated_dt

	)
	select 
		 a.make
		,a.make as make_desc
		,a.model
		,a.model as model_desc
		,a.modelyear
		,2 as vertical_id
		,suser_name()
		,getdate()
		,suser_name()
		,getdate()
	from 
		#temp as a 
	left outer join 
		clictell_auto_master.master.vehicle_makemodel b (nolock) on 
									a.make = b.make 
									and a.model = b.model 
									and a.modelyear = b.modelyear
	where 
		b.makemodel_id is null


	--returning modified make model years
	select * from #temp
END